sudo: required
services:
- docker

env:
  global:
  - DOCKER_EXEC_ROOT="sudo docker exec -it -u root test_container"
  - DOCKER_EXEC="sudo docker exec -it test_container"
  - BINTRAY_USER=laarid
  - BINTRAY_REPO=main
  - BINTRAY_COMPONENT=main
  - BINTRAY_ARCH=all

addons:
  apt:
    packages:
    - dpkg-dev

before_install:
- JOB_SUITE=$(dpkg-parsechangelog | grep ^Distribution | cut -d ' ' -f2)
- sudo docker run --detach --interactive --tty
    --name test_container
    --volume ${TRAVIS_BUILD_DIR%${TRAVIS_REPO_SLUG}}:${TRAVIS_BUILD_DIR%${TRAVIS_REPO_SLUG}}
    buildpack-deps:${JOB_SUITE}
    /bin/bash

install:
- ${DOCKER_EXEC_ROOT} apt-get update -qq
- ${DOCKER_EXEC_ROOT} apt-get install --no-install-recommends --yes devscripts equivs
- ${DOCKER_EXEC_ROOT} mk-build-deps -i -s sudo -t 'apt-get -o Debug::pkgProblemResolver=yes --no-install-recommends -y' ${TRAVIS_BUILD_DIR}/debian/control

script:
- ${DOCKER_EXEC} /bin/sh -c "cd ${TRAVIS_BUILD_DIR}; debuild --preserve-env --preserve-envvar PATH -i -us -uc -b"

before_deploy:
- |
  cat debian/bintray.json.in | \
  sed -e "s#@BINTRAY_PACKAGE@#$(cat debian/control | grep ^Source: | awk '{print $2}')#g" \
  -e "s#@BINTRAY_USER@#${BINTRAY_USER}#g" \
  -e "s#@BINTRAY_REPO@#${BINTRAY_REPO}#g" \
  -e "s#@BINTRAY_DESC@#$(cat debian/control | grep -m1 ^Description: | cut -d ' ' -f2-)#g" \
  -e "s#@GITHUB_REPO@#${TRAVIS_REPO_SLUG}#g" \
  -e "s,@BINTRAY_VERSION@,${TRAVIS_TAG#v},g" \
  -e "s#@BINTRAY_RELEASE_DATE@#$(cat debian/changelog | grep -m 1 '^ -- ' | sed 's,^.*  ,,')#g" \
  -e "s#@BINTRAY_OUTDIR@#$(dirname ${TRAVIS_BUILD_DIR})#g" \
  -e "s#@BINTRAY_POOLABBR@#$(cat debian/control | grep ^Source: | awk '{print $2}' | cut -c1)#g" \
  -e "s#@BINTRAY_SUITE@#${JOB_SUITE}#g" \
  -e "s#@BINTRAY_COMPONENT@#${BINTRAY_COMPONENT}#g" \
  -e "s#@BINTRAY_ARCH@#${BINTRAY_ARCH}#g" | \
  tee debian/bintray.json

deploy:
- provider: bintray
  file: debian/bintray.json
  user: vicamo
  key:
    secure: "HiMDb9xWe43W+XmhjQjoDGFD2fkA/qYYUD7dFbpRlpF8fNU/zmwHTw6di/0dwVNfv2wt268fkIiK5GzmnbR62giOtXLTEPUj/ef5gtJCg/xvt2U6j0/T5Wl4+glSq9wV0tbtnz4FWydHuQdP4avAVmbo8xYLM6Yqv442aniqhkLwxkaxRlwMhxfNouKRx/tTaQGSd+qOTTrFlGAfsbQTJptQTM9apPe2nhLHZ78qLvxvjptRIbKTEYfHRHC35JdqNVtnx5yXBhB3PIsiHrlGK2ERdwJd3TRlilgbCIdN5LQSEEATDvZ3qpvy9lh1pk+M0gBSo+BEPGDxOXqGpH92bwjAG67jUZI/p/0/NJYqu4Ukmvs1qMeCXu38kem6ZXYWH+F1jQ3z983S6IC5+vSZCINNK5c0YieLTaaz8C4+4y3GDeACow0+tbcbZTeiKYHG65fDD9Rj9DWBUEgq+6cgE3S+17L0rYt04FixNHcoXZpD/tNoM8KcfwlhYq3pZRVO+B7bOjZa/SuGzuPj4uYNgKfcIsYsZHHjA2PQsbPlcqunTc3kCq8oi5OkGu+nGDI3rnvb1DcZeRswh8cRcC5ohQVSM0JqO67miPxjWD48ye30gMB2kvZhBf1iXFLaBqveZsxN43Q/9TJP+t3BntEJIOUwajGOSWR/3Wvaymb6gDk="
  on:
    tags: true

notifications:
  slack:
    rooms:
    - secure: "PY3/3lAmA5wdH1SY3g708M2y2JWT3Jeah1IiF4gs7bxtNr3GyIaIgD1Ldy1X2pSVDtxkTJEDaBrxI9a59q8z3wEMy6z8d8C8PsFzx83myf+FYisColKMdMfeTGZepXL7P7ItQOtAvahCi1CIatugshtw4J9ApjJPPktPN7JuyRbILLUqf2MK2Jx7LLm6UrQ315iqX5nUeK5Id/eALM0a8C8CLojCJqJ77zMtRG1PZaevGfQVMVrq08yJaAEBVbpdnqaL+tS/t4hOPInw4Z0vWsqthOM3h5Hx7MSL94gW3NhD/aLszih3D3Qk7ClCHKo5rfiTe0cJpPADELPnwj+S87Jbf3dq+M8Bt5ckPbdYpKH2YKebKwjKofbu6UXzmLc85fX1p7PACyaZab2fXcXgl3E6TxSCzffDLVNetkqU7OXuTI9RGnj6zkUwREJ5zh/ZOsoGDhyG21U86HUQFklCIIiSxD92h169+4TZEUWnP4QRiDcrX+jNBZ9ezsZFG2195GQ3uQc0Afk0gspdKKcjB850QAcrJHsVulqQkNdlsOTwUlEzzgIoy+oKU/lGX93mO9CWaVDjGtvbbc2cRYgq/ycXrNtOqHpwZTSikyU3rmqNVyUw5SJZMhl+4OW5W0WAWHgHiOUEe+2rKAn+rq6zt6BX0G9FlbBKNl+JcD6LJtk="
